name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # change this to your default branch name if it's not 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # you can specify another version if you want

    - name: Install Dependencies
      run: yarn install  # or 'npm install' if you're not using yarn

    - name: Build Project
      run: yarn build  # or 'npm run build' if you're not using yarn

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN_GITHUB }}
        publish_dir: ./dist  # this directory should contain your built assets, update if it's different
